name: Release

on:
  push:
    branches:
      - "*"

jobs:
  list-projects:
    if: "${{ !contains(github.event.head_commit.message, '[ci skip]') }}"

    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.list-plugins.outputs.paths }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: List Plugins
        id: list-plugins
        run: echo "::set-output name=paths::$(ls -d plugins/*/ |  jq -R -s -c 'split("\n")[:-1] | .+ ["sauron-core/", "sauron-plugin-archetype/", "sauron-service/"]')"

  package-and-publish:
    needs: list-projects
    strategy:
      max-parallel: 1
      matrix:
        path: ${{ fromJSON(needs.list-projects.outputs.paths) }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sauron-service:
              - 'sauron-service/**'
            src:
              - '${{ matrix.path }}**'

      - name: Update local git repository. It is needed because other jobs might have released a new version
        run: git pull

      - name: Maven release and publish
        if: steps.changes.outputs.src == 'true'
        uses: qcastel/github-actions-maven-release@v1.12.16
        with:
          access-token: ${{ secrets.FREE_NOW_GITHUB_ACCESS_TOKEN }}
          release-branch-name: "main"
          maven-args: "-DskipTests -DskipITs"
          git-release-bot-name: "free-now-github"
          git-release-bot-email: "70742378+free-now-github@users.noreply.github.com"
          git-skip-sanity-check: ""
          ssh-private-key: ${{ secrets.FREE_NOW_GITHUB_PRIVATE_KEY }}
          maven-project-folder: ${{ matrix.path }}
          maven-repo-server-id: ossrh
          maven-repo-server-username: ${{ secrets.FREE_NOW_GITHUB_USER }}
          maven-repo-server-password: ${{ secrets.FREE_NOW_MAVEN_ACCESS_TOKEN }}
          gpg-enabled: true
          gpg-key-id: ${{ secrets.FREE_NOW_GPG_KEY_ID }}
          gpg-key: ${{ secrets.FREE_NOW_GPG_KEY }}
          gpg-passphrase: ${{ secrets.FREE_NOW_GPG_PASSPHRASE }}
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk/

      - name: Get previous tag
        if: steps.changes.outputs.src == 'true'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Github Release
        if: steps.changes.outputs.sauron-service == 'true'
        uses: marvinpinto/action-automatic-releases@v1.1.0
        with:
          repo_token: ${{ secrets.FREE_NOW_GITHUB_ACCESS_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
          files: |
            LICENSE
            SECURITY.md
            sauron-service/target/${{ steps.previoustag.outputs.tag }}.pom?(.)*
            sauron-service/target/${{ steps.previoustag.outputs.tag }}.jar?(.)*
            sauron-service/target/${{ steps.previoustag.outputs.tag }}-sources.jar?(.)*
            sauron-service/target/${{ steps.previoustag.outputs.tag }}-javadoc.jar?(.)*

      - name: Publish to Registry
        if: steps.changes.outputs.sauron-service == 'true'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: freenow/sauron
          username: ${{ secrets.FREE_NOW_DOCKER_HUB_USER }}
          password: ${{ secrets.FREE_NOW_DOCKER_HUB_TOKEN }}
          default_branch: main
          workdir: sauron-service/

